theme: jekyll-theme-minimal
title: Vinod Ponmanadiyil
description: Technology Leader | Product Development | GenAI | Cloud Computing
show_downloads: false

# Custom CSS
markdown: kramdown
highlighter: rouge

# Assets
assets:
  css: assets/css
